name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - development

jobs:
  setup:
    runs-on: self-hosted

    outputs:
      lowercase: ${{ steps.lowercase.outputs.LOWERCASE }}
      is_pr: ${{ steps.pr.outputs.IS_PR }}
      tag_name: ${{ steps.tag.outputs.TAG_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        id: lowercase
        run: echo "LOWERCASE=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

      - name: Check if currently in a pull request
        id: pr
        run: echo "IS_PR=$(test -n "${{ github.event.pull_request }}" && echo "true" || echo "false")" >> $GITHUB_OUTPUT

      - name: Create the tag name
        id: tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "TAG_NAME=latest" >> $GITHUB_OUTPUT
          else
            if [[ "${{ steps.pr.outputs.IS_PR }}" == "true" ]]; then
              echo "TAG_NAME=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            else
              echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            fi
          fi

  build-and-push:
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ needs.setup.outputs.lowercase }}/authentication-proxy:${{ needs.setup.outputs.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
